#!/bin/bash

iDIR="$HOME/.config/hypr/mako/icons/"

# Get Volume
get_volume() {
	volume=$(pamixer --get-volume)
	echo "$volume"
}
get_volume_mic() {
	volume_mic=$(pamixer --default-source --get-volume)
	echo "$volume_mic"
}

# Get icons
get_icon() {
	current=$(get_volume)
	if [[ "$current" -eq "0" ]]; then
		echo "$iDIR/volume-mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "$iDIR/volume-low.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$iDIR/volume-mid.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo "$iDIR/volume-high.png"
	fi
}

get_icon_mic() {
	current=$(get_volume_mic)
	if [[ "$current" -eq "0" ]]; then
		echo "$iDIR/microphone-mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "100") ]]; then
		echo "$iDIR/microphone.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume)"
}
notify_user_mic() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon_mic)" "Volume : $(get_volume_mic)"
}

# Increase Volume
inc_volume() {
	pamixer -i 5 && notify_user
}
inc_volume_mic() {
	pamixer --default-source -i 5 && notify_user_mic
}
# Decrease Volume
dec_volume() {
	pamixer -d 5 && notify_user
}
dec_volume_mic() {
	pamixer --default-source -d 5 && notify_user_mic
}

# Toggle Mute
toggle_mute() {
	if [ "$(pamixer --get-mute)" == "false" ]; then
		pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume OFF"
	elif [ "$(pamixer --get-mute)" == "true" ]; then
		pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume ON"
	fi
}

# Toggle Mic
toggle_mic() {
	if [ "$(pamixer --default-source 66 --get-mute)" == "false" ]; then
		pamixer -m --default-source 66 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone OFF"
	elif [ "$(pamixer --default-source 66 --get-mute)" == "true" ]; then
		pamixer -u --default-source 66 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone ON"
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--dec-mic" ]]; then
	dec_volume_mic
elif [[ "$1" == "--inc-mic" ]]; then
	inc_volume_mic
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
	get_icon
elif [[ "$1" == "--get-icon-mic" ]]; then
	get_icon_mic
else
	get_volume
fi
