#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
mako &

# Lauch statusbar (waybar)
waybar &

# Xauthority
${SCRIPTSDIR}/xauthority &

dex $HOME/.config/autostart/arcolinux-welcome-app.desktop &


nm-applet --indicator &
wl-paste --watch cliphist store &
swww init

#insync start &
#dropbox &
#telegram-desktop &
#discord &
#nm-applet --indicator
#variety &
